name: Workflow

on: [push, pull_request]

jobs:
  pipeline:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set Node.js 13.x
        uses: actions/setup-node@master
        with:
          node-version: 13.x

      - name: Run install
        run: npm install

      - name: Run test
        run: npm run test
