name: Workflow

on: [push, pull_request]

jobs:
  pipeline:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Run install
        run: yarn install

      - name: Run test
        run: yarn run test
